### ISSUE TITLE
Keep the POD in non-running state for a period of time

### ISSUE THREAD

**Issue by zhufanqin** [chaos-mesh/rfcs#33] opened 2022-01-12 02:50 UTC
There is a Fault scenario that can keep the POD in non-running state for a period of time, but the fault of POD kill can`t keep the POD in non-running state for a period of time.

**Comment by STRRL** [comment] 2022-01-12 02:55
Hi @zhufanqin, did you try "pod-failure"? I think "pod-failure" could works on this scenario.

**Comment by zhufanqin** [comment] 2022-01-12 03:02
I did，but the actual failure time is much smaller than the set, which is not ideal

**Comment by STRRL** [comment] 2022-01-12 03:04
I think the expected behavior of "pod-failure" is extremely the same as what you say. How about opening a bug report issue on chaos-mesh/chaos-mesh?

**Comment by YangKeao** [comment] 2022-01-12 03:57
@STRRL I though that what @zhufanqin needs is to not to use `pause` image, as the `pause` image will actually run (though, not the original image). He needs the pod to stop in a not running condition. (Please correct me if I was wrong)

As I remembered, we have discussed about this issue with @WangXiangUSTC in the weekly meetings several weeks ago 🤔

**Comment by STRRL** [comment] 2022-01-13 03:56
I am going to close this issue because https://github.com/chaos-mesh/chaos-mesh/issues/2776 was created. :)

Feel free to reopen it if anybody has anything to append

**Closed by STRRL** 2022-01-13 03:56 UTC
